### ISSUE TITLE
[2023-10-05] TODO

### ISSUE THREAD

**Issue by cksghkd123** [NodesOnTree/gumi2inside-django#4]
# Todo
### 류
- 홈화면 수정
- 게시글 이미지 업로드 업데이트

### 유
- 홈화면 수정
- 로그인 model, modelform
- base template에서 nav 바 로그인 버튼 추가 

### 윤
- 로그인 view
- 로그인 template

### 이
- 로그인 view
- 회원가입 template

### 조
- 로그인 view
- mypage template

### 황
- Jenkins 로 CI/CD 구축

**Comment by osh-lang** [comment]
홈 화면 수정하겠습니다.

**Comment by LEESEOM** [comment]
나는 회원가입 view template 할게용

**Comment by jyYoon96** [comment]
저는 로그인 view templates 합니다
